info:
	@echo "Makefile is your friend"
	@awk 'BEGIN {FS = ":.*?## "} /^[a-zA-Z_-]+:.*?## / {printf "\033[36m%-20s\033[0m %s\n", $$1, $$2}' $(MAKEFILE_LIST)

start: ## start the application
	./infra/start.sh

docker-up: ## up the docker service
	./infra/docker-up.sh

docker-stop: ## stop the docker service
	./infra/docker-stop.sh

docker-down: ## remove the docker service
	./infra/docker-down.sh
